import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { readFileSync } from "fs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <div dangerouslySetInnerHTML={{ __html: readFileSync('./public/angular-modal/browser/index.html').toString() }} /> */}
        {children}
       
        </body>
    </html>
  );
}
